// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: app/app.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PickListType int32

const (
	PickListType_TYPE_ADD    PickListType = 0
	PickListType_TYPE_REMOVE PickListType = 1
)

// Enum value maps for PickListType.
var (
	PickListType_name = map[int32]string{
		0: "TYPE_ADD",
		1: "TYPE_REMOVE",
	}
	PickListType_value = map[string]int32{
		"TYPE_ADD":    0,
		"TYPE_REMOVE": 1,
	}
)

func (x PickListType) Enum() *PickListType {
	p := new(PickListType)
	*p = x
	return p
}

func (x PickListType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PickListType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_app_proto_enumTypes[0].Descriptor()
}

func (PickListType) Type() protoreflect.EnumType {
	return &file_app_app_proto_enumTypes[0]
}

func (x PickListType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PickListType.Descriptor instead.
func (PickListType) EnumDescriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{0}
}

type PickRealMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PickMap map[string]PickListType `protobuf:"bytes,1,rep,name=pick_map,json=pickMap,proto3" json:"pick_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=app.PickListType"`
}

func (x *PickRealMap) Reset() {
	*x = PickRealMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickRealMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickRealMap) ProtoMessage() {}

func (x *PickRealMap) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickRealMap.ProtoReflect.Descriptor instead.
func (*PickRealMap) Descriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{0}
}

func (x *PickRealMap) GetPickMap() map[string]PickListType {
	if x != nil {
		return x.PickMap
	}
	return nil
}

type PickFuture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *PickFuture) Reset() {
	*x = PickFuture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PickFuture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickFuture) ProtoMessage() {}

func (x *PickFuture) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickFuture.ProtoReflect.Descriptor instead.
func (*PickFuture) Descriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{1}
}

func (x *PickFuture) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type WSMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*WSMessage_FutureDetail
	//	*WSMessage_FutureTick
	//	*WSMessage_HistoryKbar
	//	*WSMessage_Snapshot
	//	*WSMessage_TradeIndex
	Data isWSMessage_Data `protobuf_oneof:"data"`
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{2}
}

func (m *WSMessage) GetData() isWSMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *WSMessage) GetFutureDetail() *FutureDetailMessage {
	if x, ok := x.GetData().(*WSMessage_FutureDetail); ok {
		return x.FutureDetail
	}
	return nil
}

func (x *WSMessage) GetFutureTick() *FutureRealTimeTickMessage {
	if x, ok := x.GetData().(*WSMessage_FutureTick); ok {
		return x.FutureTick
	}
	return nil
}

func (x *WSMessage) GetHistoryKbar() *HistoryKbarResponse {
	if x, ok := x.GetData().(*WSMessage_HistoryKbar); ok {
		return x.HistoryKbar
	}
	return nil
}

func (x *WSMessage) GetSnapshot() *SnapshotMessage {
	if x, ok := x.GetData().(*WSMessage_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *WSMessage) GetTradeIndex() *TradeIndex {
	if x, ok := x.GetData().(*WSMessage_TradeIndex); ok {
		return x.TradeIndex
	}
	return nil
}

type isWSMessage_Data interface {
	isWSMessage_Data()
}

type WSMessage_FutureDetail struct {
	FutureDetail *FutureDetailMessage `protobuf:"bytes,1,opt,name=future_detail,json=futureDetail,proto3,oneof"`
}

type WSMessage_FutureTick struct {
	FutureTick *FutureRealTimeTickMessage `protobuf:"bytes,2,opt,name=future_tick,json=futureTick,proto3,oneof"`
}

type WSMessage_HistoryKbar struct {
	HistoryKbar *HistoryKbarResponse `protobuf:"bytes,3,opt,name=history_kbar,json=historyKbar,proto3,oneof"`
}

type WSMessage_Snapshot struct {
	Snapshot *SnapshotMessage `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof"`
}

type WSMessage_TradeIndex struct {
	TradeIndex *TradeIndex `protobuf:"bytes,5,opt,name=trade_index,json=tradeIndex,proto3,oneof"`
}

func (*WSMessage_FutureDetail) isWSMessage_Data() {}

func (*WSMessage_FutureTick) isWSMessage_Data() {}

func (*WSMessage_HistoryKbar) isWSMessage_Data() {}

func (*WSMessage_Snapshot) isWSMessage_Data() {}

func (*WSMessage_TradeIndex) isWSMessage_Data() {}

type TradeIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tse    *IndexStatus `protobuf:"bytes,1,opt,name=tse,proto3" json:"tse,omitempty"`
	Otc    *IndexStatus `protobuf:"bytes,2,opt,name=otc,proto3" json:"otc,omitempty"`
	Nasdaq *IndexStatus `protobuf:"bytes,3,opt,name=nasdaq,proto3" json:"nasdaq,omitempty"`
	Nf     *IndexStatus `protobuf:"bytes,4,opt,name=nf,proto3" json:"nf,omitempty"`
}

func (x *TradeIndex) Reset() {
	*x = TradeIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeIndex) ProtoMessage() {}

func (x *TradeIndex) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeIndex.ProtoReflect.Descriptor instead.
func (*TradeIndex) Descriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{3}
}

func (x *TradeIndex) GetTse() *IndexStatus {
	if x != nil {
		return x.Tse
	}
	return nil
}

func (x *TradeIndex) GetOtc() *IndexStatus {
	if x != nil {
		return x.Otc
	}
	return nil
}

func (x *TradeIndex) GetNasdaq() *IndexStatus {
	if x != nil {
		return x.Nasdaq
	}
	return nil
}

func (x *TradeIndex) GetNf() *IndexStatus {
	if x != nil {
		return x.Nf
	}
	return nil
}

type IndexStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BreakCount int64   `protobuf:"varint,1,opt,name=break_count,json=breakCount,proto3" json:"break_count,omitempty"`
	PriceChg   float64 `protobuf:"fixed64,2,opt,name=price_chg,json=priceChg,proto3" json:"price_chg,omitempty"`
}

func (x *IndexStatus) Reset() {
	*x = IndexStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatus) ProtoMessage() {}

func (x *IndexStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatus.ProtoReflect.Descriptor instead.
func (*IndexStatus) Descriptor() ([]byte, []int) {
	return file_app_app_proto_rawDescGZIP(), []int{4}
}

func (x *IndexStatus) GetBreakCount() int64 {
	if x != nil {
		return x.BreakCount
	}
	return 0
}

func (x *IndexStatus) GetPriceChg() float64 {
	if x != nil {
		return x.PriceChg
	}
	return 0
}

var File_app_app_proto protoreflect.FileDescriptor

var file_app_app_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x70, 0x1a, 0x17, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x65, 0x72, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0b, 0x50, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x6c, 0x4d,
	0x61, 0x70, 0x12, 0x38, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x52,
	0x65, 0x61, 0x6c, 0x4d, 0x61, 0x70, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x1a, 0x4d, 0x0a, 0x0c,
	0x50, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x50, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a, 0x0a, 0x50,
	0x69, 0x63, 0x6b, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xd6, 0x02,
	0x0a, 0x09, 0x57, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x66,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x46,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x47, 0x0a, 0x0b, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0a, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x43, 0x0a, 0x0c, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6b, 0x62, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x4b, 0x62, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4b, 0x62, 0x61, 0x72,
	0x12, 0x38, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x48, 0x00, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x0a, 0x03, 0x74, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x74, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x6f, 0x74, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x6f, 0x74, 0x63, 0x12, 0x28, 0x0a,
	0x06, 0x6e, 0x61, 0x73, 0x64, 0x61, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x6e, 0x61, 0x73, 0x64, 0x61, 0x71, 0x12, 0x20, 0x0a, 0x02, 0x6e, 0x66, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x02, 0x6e, 0x66, 0x22, 0x4b, 0x0a, 0x0b, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62,
	0x72, 0x65, 0x61, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x5f, 0x63, 0x68, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x43, 0x68, 0x67, 0x2a, 0x2d, 0x0a, 0x0c, 0x50, 0x69, 0x63, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41,
	0x44, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d,
	0x4f, 0x56, 0x45, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_app_proto_rawDescOnce sync.Once
	file_app_app_proto_rawDescData = file_app_app_proto_rawDesc
)

func file_app_app_proto_rawDescGZIP() []byte {
	file_app_app_proto_rawDescOnce.Do(func() {
		file_app_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_app_proto_rawDescData)
	})
	return file_app_app_proto_rawDescData
}

var file_app_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_app_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_app_proto_goTypes = []interface{}{
	(PickListType)(0),                 // 0: app.PickListType
	(*PickRealMap)(nil),               // 1: app.PickRealMap
	(*PickFuture)(nil),                // 2: app.PickFuture
	(*WSMessage)(nil),                 // 3: app.WSMessage
	(*TradeIndex)(nil),                // 4: app.TradeIndex
	(*IndexStatus)(nil),               // 5: app.IndexStatus
	nil,                               // 6: app.PickRealMap.PickMapEntry
	(*FutureDetailMessage)(nil),       // 7: forwarder.FutureDetailMessage
	(*FutureRealTimeTickMessage)(nil), // 8: forwarder.FutureRealTimeTickMessage
	(*HistoryKbarResponse)(nil),       // 9: forwarder.HistoryKbarResponse
	(*SnapshotMessage)(nil),           // 10: forwarder.SnapshotMessage
}
var file_app_app_proto_depIdxs = []int32{
	6,  // 0: app.PickRealMap.pick_map:type_name -> app.PickRealMap.PickMapEntry
	7,  // 1: app.WSMessage.future_detail:type_name -> forwarder.FutureDetailMessage
	8,  // 2: app.WSMessage.future_tick:type_name -> forwarder.FutureRealTimeTickMessage
	9,  // 3: app.WSMessage.history_kbar:type_name -> forwarder.HistoryKbarResponse
	10, // 4: app.WSMessage.snapshot:type_name -> forwarder.SnapshotMessage
	4,  // 5: app.WSMessage.trade_index:type_name -> app.TradeIndex
	5,  // 6: app.TradeIndex.tse:type_name -> app.IndexStatus
	5,  // 7: app.TradeIndex.otc:type_name -> app.IndexStatus
	5,  // 8: app.TradeIndex.nasdaq:type_name -> app.IndexStatus
	5,  // 9: app.TradeIndex.nf:type_name -> app.IndexStatus
	0,  // 10: app.PickRealMap.PickMapEntry.value:type_name -> app.PickListType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_app_proto_init() }
func file_app_app_proto_init() {
	if File_app_app_proto != nil {
		return
	}
	file_forwarder_history_proto_init()
	file_forwarder_realtime_proto_init()
	file_forwarder_basic_proto_init()
	file_forwarder_mq_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickRealMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PickFuture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_app_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WSMessage_FutureDetail)(nil),
		(*WSMessage_FutureTick)(nil),
		(*WSMessage_HistoryKbar)(nil),
		(*WSMessage_Snapshot)(nil),
		(*WSMessage_TradeIndex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_app_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_app_proto_goTypes,
		DependencyIndexes: file_app_app_proto_depIdxs,
		EnumInfos:         file_app_app_proto_enumTypes,
		MessageInfos:      file_app_app_proto_msgTypes,
	}.Build()
	File_app_app_proto = out.File
	file_app_app_proto_rawDesc = nil
	file_app_app_proto_goTypes = nil
	file_app_app_proto_depIdxs = nil
}
