# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/app.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from toc_trade_pb.forwarder import history_pb2 as forwarder_dot_history__pb2
from toc_trade_pb.forwarder import realtime_pb2 as forwarder_dot_realtime__pb2
from toc_trade_pb.forwarder import basic_pb2 as forwarder_dot_basic__pb2
from toc_trade_pb.forwarder import mq_pb2 as forwarder_dot_mq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapp/app.proto\x12\x03\x61pp\x1a\x17\x66orwarder/history.proto\x1a\x18\x66orwarder/realtime.proto\x1a\x15\x66orwarder/basic.proto\x1a\x12\x66orwarder/mq.proto\"\x81\x01\n\x0bPickRealMap\x12/\n\x08pick_map\x18\x01 \x03(\x0b\x32\x1d.app.PickRealMap.PickMapEntry\x1a\x41\n\x0cPickMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0e\x32\x11.app.PickListType:\x02\x38\x01\"\x1a\n\nPickFuture\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x99\x02\n\tWSMessage\x12\x37\n\rfuture_detail\x18\x01 \x01(\x0b\x32\x1e.forwarder.FutureDetailMessageH\x00\x12;\n\x0b\x66uture_tick\x18\x02 \x01(\x0b\x32$.forwarder.FutureRealTimeTickMessageH\x00\x12\x36\n\x0chistory_kbar\x18\x03 \x01(\x0b\x32\x1e.forwarder.HistoryKbarResponseH\x00\x12.\n\x08snapshot\x18\x04 \x01(\x0b\x32\x1a.forwarder.SnapshotMessageH\x00\x12&\n\x0btrade_index\x18\x05 \x01(\x0b\x32\x0f.app.TradeIndexH\x00\x42\x06\n\x04\x64\x61ta\"\x8a\x01\n\nTradeIndex\x12\x1d\n\x03tse\x18\x01 \x01(\x0b\x32\x10.app.IndexStatus\x12\x1d\n\x03otc\x18\x02 \x01(\x0b\x32\x10.app.IndexStatus\x12 \n\x06nasdaq\x18\x03 \x01(\x0b\x32\x10.app.IndexStatus\x12\x1c\n\x02nf\x18\x04 \x01(\x0b\x32\x10.app.IndexStatus\"5\n\x0bIndexStatus\x12\x13\n\x0b\x62reak_count\x18\x01 \x01(\x03\x12\x11\n\tprice_chg\x18\x02 \x01(\x01*-\n\x0cPickListType\x12\x0c\n\x08TYPE_ADD\x10\x00\x12\x0f\n\x0bTYPE_REMOVE\x10\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_PICKREALMAP_PICKMAPENTRY']._loaded_options = None
  _globals['_PICKREALMAP_PICKMAPENTRY']._serialized_options = b'8\001'
  _globals['_PICKLISTTYPE']._serialized_start=756
  _globals['_PICKLISTTYPE']._serialized_end=801
  _globals['_PICKREALMAP']._serialized_start=117
  _globals['_PICKREALMAP']._serialized_end=246
  _globals['_PICKREALMAP_PICKMAPENTRY']._serialized_start=181
  _globals['_PICKREALMAP_PICKMAPENTRY']._serialized_end=246
  _globals['_PICKFUTURE']._serialized_start=248
  _globals['_PICKFUTURE']._serialized_end=274
  _globals['_WSMESSAGE']._serialized_start=277
  _globals['_WSMESSAGE']._serialized_end=558
  _globals['_TRADEINDEX']._serialized_start=561
  _globals['_TRADEINDEX']._serialized_end=699
  _globals['_INDEXSTATUS']._serialized_start=701
  _globals['_INDEXSTATUS']._serialized_end=754
# @@protoc_insertion_point(module_scope)
